# Generated by Django 2.1 on 2020-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('imageIn', models.ImageField(upload_to='images/')),
                ('videoIn', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
